CODE_OF_CONDUCT.md
I've added code of conduct.
Fixes #150 
=> CodeOfConduct added

Form Wave/style.css
=> changed the size of back ground video and label color

Registrationform.html, Registrationformhrmlcss.html
Fixes #(234)
Replace `234` with the issue number which is fixed in this PR
Created Registration using HTML AND CSS.
This form consist of
1 First Name
2 Last Name
3 Email ID
4 Phone number
5 Branch 
6 Year
7 Gender
For every title created seperate classes.
"I havn't put background image because of copyright issue but have implemented this feature".
=> Registration form

StopWatch/index.html, StopWatch/script.js, StopWatch/style.css
=> I have created a stop watch.

Palindrome Checker/index.html, Palindrome Checker/script.js, Palindrome Checker/style.css
=> Created a Palindrome Checker

.vscode/settings.json, Tip Calculator/script.js, Tip Calculator/style.css, Tip Calculator/tip.html
I have added the tip calculator. Can you check it ?
Fixes #291 
=> Added tip calculator

DrinkWater/index.html, DrinkWater/script.js, DrinkWater/style.css
This app simply calculate the amount of water that we drink in day and will simply update or delete the quantity using api calls in javascript function
=> added code for Drink Water App

Scroll animation/index.html, Scroll animation/script.js, Scroll animation/style.css
Signed-off-by: harsh6768-svg <1905391@kiit.ac.in>
This is the scroll animation project which makes the scrolling easier and has concept of HTML  CSS and JS used inside it
Fixes #319
Replace #319 with the issue number which is fixed in this PR
=> Scroll Animation Project

GridDemo/index.css, GridDemo/index.html
=> Added CSS grid demo as per CSS Grid demo #345

mobile tab navigation/index.html, mobile tab navigation/script.js, mobile tab navigation/style.css
Signed-off-by: harsh6768-svg <1905391@kiit.ac.in>
just with the concept of HTML CSS AND JS a mobile tab kind of ui is designed for the application
Fixes #336
Replace #336 with the issue number which is fixed in this PR
=> Mobile TAB NAVIGATION 

Chess Clone/app.js, Chess Clone/index.html, Chess Clone/style.css
I have successfully added a chess clone project using HTML, CSS, JS
Fixes #316 
Replace #316  with the issue number which is fixed in this PR
=> 🚀Feat: Added Chess Clone (#316)

Blur_Boom_HTML_CSS/index.html, Blur_Boom_HTML_CSS/script.js, Blur_Boom_HTML_CSS/style.css
=> feat: Add BlurBoom project

Button ripple effect/index.html, Button ripple effect/script.js, Button ripple effect/style.css
Signed-off-by: Hrithik <1905394@gmail.com>
This project is used to create a ripple effect using a concept of ripple property of css. 
Fixes #323 
Replace #323 with the issue number which is fixed in this PR
=> BUTTON RIPPLE EFFECT

CovidData/index.html
This got inserted with the previous PR, So I did a little change.
Fixes #346
=> Added as per issue Covid data getter #346

age-calculator/style.css
I have added styles to the Calculate button and changed the cursor type to pointer
Fixes #353
=> add button hover effect and change cursor type

FontAwesome icon Background Animation Effects/index.html, FontAwesome icon Background Animation Effects/style.css
=> FontAwesome Icon

Microsoft Landing Page/index.html, Microsoft Landing Page/phone.css, Microsoft Landing Page/style.css
=> Microsoft Landing Page

Faq Collapse/index.html, Faq Collapse/script.js, Faq Collapse/style.css
=> Faq Collapse

README.md
Just added screenshot no. 113 of frontend developer portfolio site
=> added screenshot of frontend developer portfolio

README.md
Signed-off-by: Hemant Sachdeva <hemant.evolver@gmail.com>
Updated link to a screenshot 
=> chore: Correction in Gradient Background Generator screenshot url

Sticky Notes/index.html, Sticky Notes/style.js, Sticky Notes/styling.css
Added a new project named- Sticky Notes
=> added project

Color_Code_Converter/assets/style.css, Color_Code_Converter/index.html, Color_Code_Converter/scripts/app.js
Added Color Code Converter that converts between different color code formats such as RGB, CMYK, Hex, & Hsl
Fixes #552 
=> Added ColorCodeConverter files

README.md
Added Binary clock image in readme.md
Fixes #562
=> Fixes #562

Random Anime Profile/index.html, Random Anime Profile/script.js, Random Anime Profile/style.css
hey, Project admin I'm a GSSOC participant and as you assign me the issue to work on that I create the project that I want to add my random anime profile pic generator to the list I complete the issue and now I'm creating the pull request regarding that I get busy due to my offline college so that's why it takes time to me, this project is very useful for those who don't have the knowledge of working with web API in javascript and how the fetch function works. and I'm attaching the screenshot and deployMent link please go through it and  I hope that you will go through my pull request and merge it thanking you...
Fixes ISSUE #[560](https://github.com/Ayush7614/Bundli-Frontend/issues/560#issue-1161220347)
=> Added Random Anime profile pics generator to the list..

BaseX_Calculator/app.js, BaseX_Calculator/index.html, BaseX_Calculator/style.css, Color_Code_Converter/readme.md
I would like to add a simple calculator that converts between any desired base, example: `from base-3 to base-6` , `from binary to octal` , `from hexadecimal to decimal`, .. etc
Fixes #577 
https://user-images.githubusercontent.com/64689436/159027749-3cb320ed-b783-4b1b-bec4-0bb33f74e22d.mp4
=> Added baseX calc files

card/index.html, card/style.css
In this project on clicking the card header the card expands.
Fixes #590
-  My code follows the style guidelines(Clean Code) of this project
-  I have performed a self-review of my own code
-  I have commented my code, particularly in the hard-to-understand area
-  I have added tests/screenshots(if any) that prove my fix is effective or that my feature works
=> added a expadable card

Emoji Memory Game/index.html, Emoji Memory Game/index.js, Emoji Memory Game/styles.css
This is a flipping matching memory game made using html, css and js.
Fixes #605 
creenshots(if any) that prove my fix is effective or that my feature works
https://user-images.githubusercontent.com/66300439/161899426-6f768b7f-9000-478e-ad66-15920642c54b.mp4
=> Adding the memory game

Weather App/app.js, Weather App/index.html, Weather App/styles.css
A weather App Built using geolocation and openweather api
Fixes #617 
=> Final Commit of Weather Application

.vscode/settings.json, Double-Tap-Like/index.html, Double-Tap-Like/script.js, Double-Tap-Like/style.css
@gurjeetsinghvirdee  as you assign the issue to me I'm creating the pull request regarding that and I have added double tap to like image project to the current repository please go through it and I hope that you will merge my pull request. and it is not a copied project I have purchased the course 50days50project in which I have created this project.
Fixes #ISSUE [630](https://github.com/Ayush7614/Bundli-Frontend/issues/630)
=> Added Double tap to like image project.

Long Drive/README.md, Long Drive/index.html, Long Drive/style.css
A moving car animation made using HTML and CSS.
Fixes #631
=> Long Drive

Jumping square/index.html, Jumping square/style.css
Hey, project admin, I'm a GSSOC participant and as you assign me this issue to work on I have created the pull request regarding that. I have added the Jumping square animation project to the Bundli-Fontend repository please go through my Pull request and merge it. more about this is in the issue so you can give it a look.
Fixes #ISSUE [659](https://github.com/Ayush7614/Bundli-Frontend/issues/659)
@gurjeetsinghvirdee kindly review this pull request
=> Added a jumping square animation project to current repository.

Image Particle Animation/index.html, Image Particle Animation/readme.md, Image Particle Animation/script.js, Image Particle Animation/style.css
Added image particle animation effect with animation on cursor movement
Fixes  #668
=> Particle Animation for Image

CSS Energy Ball Animation Effects/index.html, CSS Energy Ball Animation Effects/style.css
An animated energy ball with CSS effect/animation feature , with some illuminating effects.
Fixes #670 
=> animated energy ball

Alarm App/app.js, Alarm App/index.html, Alarm App/preview.md, Alarm App/style.css
This PR solves the issue Alarm app
Fixes #690 
=> Issue #690 resolved Alarm app

CatGame/app.js, CatGame/index.html, CatGame/readme.md, CatGame/style.css
Cat Game Using
- Html
- Css
- Javascript
Fixes #699 
=> Issue #699 resolved : Cute Cat Dressing Room 

Vertical Image sliders/README.md, Vertical Image sliders/index.html, Vertical Image sliders/script.js, Vertical Image sliders/style.css
Vertical Image Sliders files added.... you can attach this image sliders to your next project and it'll definitely catch people's eyes
important - took reference from a  yt video
Fixes #717 
- [x ] My code follows the style guidelines(Clean Code) of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have created a helpful and easy to understand `README.md`
- [ x] My changes generate no new warnings
- [ x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works
https://user-images.githubusercontent.com/91609324/168122932-3464b6ef-baad-4a6e-a237-4bda9b0dd435.mp4
=> Vertical Image Sliders files added

Sign_Up_Login_Form/.gitignore, Sign_Up_Login_Form/app.js, Sign_Up_Login_Form/index.html, Sign_Up_Login_Form/package-lock.json
Added Email & password Authentication Method. 
Fixes #707 
=> Added Email & Password Authentication Method

Sign_Up_Login_Form/.gitignore, Sign_Up_Login_Form/app.js, Sign_Up_Login_Form/index.html, Sign_Up_Login_Form/package-lock.json
Added Google Authentication Method
Fixes #712
=> Added Google Authentication to the SignUp Login Form Project

Sign_Up_Login_Form/.gitignore, Sign_Up_Login_Form/app.js, Sign_Up_Login_Form/index.html, Sign_Up_Login_Form/package-lock.json
I have added the GitHub Authentication Method. You can refer to the screenshots added below
Fixes #713 
=> GitHub Authentication Added

Step By Step Form/index.html, Step By Step Form/readme.md, Step By Step Form/script.js, Step By Step Form/style.css
=> Stepbtstepform

Chatbot UI/index.html, Chatbot UI/readme.md, Chatbot UI/script.js, Chatbot UI/style.css
Fixes #733 
- [xx My code follows the style guidelines(Clean Code) of this project
=> Chatbot UI

TaskManagement/app.js, TaskManagement/index.html, TaskManagement/readme.md, TaskManagement/style.css
Responsive Task Management Ui
Fixes #779 
=> Issue #779 Responsive Task Management UI

news/app.js, news/failure.html, news/package-lock.json, news/package.json, news/public/style.css, news/signup.html, news/style.css, news/success.html, public/style.css
This page is made up with the help of html, css, js, json, nodejs, express. Please merge it.
=> This file contains newsletter-signup page..

loader/indexld.html, loader/styleld.css
An attractive glowing-pencil loader to add to any loading page
Fixes #(issue_no)
=> A glowing loader added!
